# render.yaml
services:
  - type: web
    name: atalian-machine-api # Render Web Hizmetine vereceğin isimle eşleşmeli
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      # DATABASE_URL artık render.yaml'den değil, Render arayüzünden manuel gelecek
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
    # pythonVersion: 3.9.18 # BU SATIRI KALDIRIYORUZ!